# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.

# Start SimpleCov for cucumber tests
require 'simplecov'
SimpleCov.start 'rails' if ENV['COVERAGE']

require 'cucumber/rails'
require 'capybara/cucumber'
require 'selenium-webdriver'

# Helper method to find Chrome binary
def which(command)
  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : [ '' ]
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exts.each do |ext|
      exe = File.join(path, "#{command}#{ext}")
      return exe if File.executable?(exe) && !File.directory?(exe)
    end
  end
  nil
end

# Use test environment for E2E tests for proper isolation
ENV['RAILS_ENV'] = 'test'

# Configure Capybara for full-stack testing
Capybara.configure do |config|
  config.default_driver = :selenium_chrome_headless
  config.javascript_driver = :selenium_chrome_headless
  config.app_host = 'http://localhost:3001'  # React frontend
  config.default_max_wait_time = 20  # Increased for CI environments
  config.server = :puma, { Silent: true }
  config.automatic_reload = false  # Disable for CI stability
end

# Configure Chrome options for headless testing with Selenium 4.8+
Capybara.register_driver :selenium_chrome_headless do |app|
  chrome_options = Selenium::WebDriver::Chrome::Options.new
  chrome_options.add_argument('--headless=new')
  chrome_options.add_argument('--no-sandbox')
  chrome_options.add_argument('--disable-dev-shm-usage')
  chrome_options.add_argument('--disable-gpu')
  chrome_options.add_argument('--disable-web-security')
  chrome_options.add_argument('--window-size=1920,1080')
  chrome_options.add_argument('--disable-extensions')
  chrome_options.add_argument('--disable-background-timer-throttling')
  chrome_options.add_argument('--disable-backgrounding-occluded-windows')
  chrome_options.add_argument('--disable-renderer-backgrounding')

  # Use Google Chrome stable with fallback options
  # Try multiple possible Chrome binary locations
  chrome_binary = ENV['GOOGLE_CHROME_BIN'] ||
                  which('google-chrome-stable') ||
                  which('google-chrome') ||
                  which('chromium-browser') ||
                  '/usr/bin/google-chrome-stable'

  chrome_options.binary = chrome_binary

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    options: chrome_options
  )
end

# By default, any exception happening in your Rails application will bubble up
# to Cucumber so that your scenario will fail. This is a different from how
# your application behaves in the production environment, where an error page will
# be rendered instead.
#
# Sometimes we want to override this default behaviour and allow Rails to rescue
# exceptions and display an error page (just like when the app is running in production).
# Typical scenarios where you want to do this is when you test your error pages.
# There are two ways to allow Rails to rescue exceptions:
#
# 1) Tag your scenario (or feature) with @allow-rescue
#
# 2) Set the value below to true. Beware that doing this globally is not
# recommended as it will mask a lot of errors for you!
#
ActionController::Base.allow_rescue = false

# Remove/comment out the lines below if your app doesn't have a database.
# For some databases (like MongoDB and CouchDB) you may need to use :truncation instead.
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end

# You may also want to configure DatabaseCleaner to use different strategies for certain features and scenarios.
# See the DatabaseCleaner documentation for details. Example:
#
#   Before('@no-txn,@selenium,@culerity,@celerity,@javascript') do
#     # { except: [:widgets] } may not do what you expect here
#     # as Cucumber::Rails::Database.javascript_strategy overrides
#     # this setting.
#     DatabaseCleaner.strategy = :truncation
#   end
#
#   Before('not @no-txn', 'not @selenium', 'not @culerity', 'not @celerity', 'not @javascript') do
#     DatabaseCleaner.strategy = :transaction
#   end
#

# Possible values are :truncation and :transaction
# The :transaction strategy is faster, but might give you threading problems.
# See https://github.com/cucumber/cucumber-rails/blob/master/features/choose_javascript_database_strategy.feature
Cucumber::Rails::Database.javascript_strategy = :truncation
